.TH priQueue.h 3 "17 Dec 2001" "TASK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
priQueue.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fR
.br
\fC#include "task.h"\fR
.br
\fC#include "../include/util/type.h"\fR
.br
\fC#include "../include/util/errorCode.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBPriQueue\fR"
.br
.ti -1c
.RI "struct \fBQueue\fR"
.br
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBSUN\fR"
.br
.ti -1c
.RI "#define \fB_PRI_QUEUE_H_\fR"
.br
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef struct \fBQueue\fR \fBTaskQueue\fR"
.br
.in -1c
.SH DEFINE DOCUMENTATION
.PP 
.SS #define SUN
.PP
\fBValue:\fR
.PP
.nf

.fi
.SS #define _PRI_QUEUE_H_
.PP
\fBValue:\fR
.PP
.nf

.fi
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef struct \fBQueue\fR TaskQueue
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for TASK from the source code.