.TH QueueBase 3 "17 Dec 2001" "TASK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QueueBase \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dbLinkQueue.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "\fBTask\fR* \fBpHead\fR"
.br
.ti -1c
.RI "\fBTask\fR* \fBpTail\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBTask\fR * QueueBase::pHead
.PP
.SS \fBTask\fR * QueueBase::pTail
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for TASK from the source code.