.TH SimpleQueue 3 "17 Dec 2001" "TASK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleQueue \- 
.SH SYNOPSIS
.br
.PP
\fC#include <queue.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBSimpleQueue\fR ()"
.br
.ti -1c
.RI "ErrorCode \fBaddQueue\fR (\fBTask\fR *_pTask)"
.br
.ti -1c
.RI "\fBTask\fR* \fBgetItem\fR (void)"
.br
.ti -1c
.RI "int \fBgetNumItem\fR (void)"
.br
.ti -1c
.RI "Boolean \fBisEmpty\fR ()"
.br
.ti -1c
.RI "void \fBprintQueue\fR (void)"
.br
.in -1c
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS SimpleQueue::SimpleQueue ()
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS ErrorCode SimpleQueue::addQueue (\fBTask\fR * _pTask)\fC [inline]\fR
.PP
.SS \fBTask\fR * SimpleQueue::getItem (void)\fC [inline]\fR
.PP
.SS int SimpleQueue::getNumItem (void)\fC [inline]\fR
.PP
.SS Boolean SimpleQueue::isEmpty (void)\fC [inline]\fR
.PP
.SS void SimpleQueue::printQueue (void)
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for TASK from the source code.