.TH task.cc 3 "17 Dec 2001" "TASK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
task.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include "../task/task.h"\fR
.br
.SS Variables

.in +1c
.ti -1c
.RI "char* \fBstrTaskState\fR []"
.br
.in -1c
.SH VARIABLE DOCUMENTATION
.PP 
.SS char * strTaskState[]
.PP
\fBInitial value:\fR
.PP
.nf
 {"Dummy", "Active", "Ready", "Dead", "SendBlocked", 
    "ReplyBlocked", "ReceiveBlocked", "EventBlocked", "PriorityInherited"}
.fi
.SH AUTHOR
.PP 
Generated automatically by Doxygen for TASK from the source code.