.TH taskDescTable.h 3 "17 Dec 2001" "TASK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
taskDescTable.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "task.h"\fR
.br
\fC#include "priQueue.h"\fR
.br
\fC#include "../task/dbLinkQueue.h"\fR
.br
\fC#include "../include/util/type.h"\fR
.br
\fC#include "../include/util/errorCode.h"\fR
.br
\fC#include <stdio.h>\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBTaskDescTable\fR"
.br
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fB_TASK_DESC_TABLE_H_\fR"
.br
.ti -1c
.RI "#define \fBSUN\fR"
.br
.in -1c
.SH DEFINE DOCUMENTATION
.PP 
.SS #define SUN
.PP
\fBValue:\fR
.PP
.nf

.fi
.SS #define _TASK_DESC_TABLE_H_
.PP
\fBValue:\fR
.PP
.nf

.fi
.SH AUTHOR
.PP 
Generated automatically by Doxygen for TASK from the source code.